### ISSUE TITLE
[TODO]: push new tagged images to Docker Hub automatically for new releases

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#911]
**Notes**
Currently, our [workflow](https://github.com/chemprop/chemprop/blob/660b8c4714d8845d1342c95a2649533436f75c40/.github/workflows/ci.yml#L178) builds and pushes changes to the `latest` image on our Docker Hub whenever we make changes to the `main` branch that pass tests. However, when we make a new version release, we have to manually push the new tagged version to Docker Hub (so that we have, for example, `v2.0.1` in addition to `latest`).

This is in contrast to our PyPI [workflow](https://github.com/chemprop/chemprop/blob/660b8c4714d8845d1342c95a2649533436f75c40/.github/workflows/ci.yml#L144) that uses the `skip-existing` keyword to try to push changes to PyPI for every update to `main`, but to only succeed when there isn't already a matching version number on PyPI. 

For Docker, I think we want to do both (continue updating a `latest` image, but also add the capability to automatically make new tagged versions for version releases).

Could we accomplish this using something like the following?
```
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push-docker-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chemprop/chemprop:latest

  build-and-push-docker-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            chemprop/chemprop:${{ env.TAG }}
            chemprop/chemprop:latest
```

There may be a cleaner way to do this, and I'm not even certain this would work.

[Related StackOverflow question](https://stackoverflow.com/questions/66017161/add-a-tag-to-a-docker-image-if-theres-a-git-tag-using-github-action)
